[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'

[tool.pyright]
pythonVersion = "3.13"
typeCheckingMode = "strict"
include = ["ryan_library", "ryan_scripts"]
extraPaths = ["vendor", "vendor/run_hy8/src"]
